services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8000" # Exposes port to other containers but NOT to localhost
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # Exposing only the frontend
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
